# yaml-language-server: $schema=https://carlos-err406.github.io/active-directory-web-manager/schemas/index.schema.json
directory:
  ldap:
    ldapURL: ldaps://localhost:636
    strictDN: true
  adminGroup: Domain Admins
