version: "3.4"

services:
  samba:
    build:
      context: samba
      dockerfile: Dockerfile
      args:
        samba_version: "4.20.0" #value selected from https://download.samba.org/pub/samba/stable
    image: samba4:latest
    container_name: directory
    env_file:
      - .env
    restart: unless-stopped
    networks:
      adwebmanagerapp.net:
        ipv4_address: ${SAMBA_AD_SERVER}

  db:
    image: postgres:16.2-alpine3.19
    container_name: adwebmanagerapp.db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - adwebmanagerapp.pgvol:/var/lib/postgresql/data
    networks:
      - adwebmanagerapp.net

  pgadmin:
    container_name: adwebmanagerapp.pgadmin
    image: dpage/pgadmin4:8.5
    env_file:
      - .env
    volumes:
      - adwebmanagerapp.pgadminvol:/var/lib/pgadmin
    ports:
      - 80:80
    networks:
      - adwebmanagerapp.net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    container_name: app
    ports:
      - 3000:3000
    depends_on:
      - db
      - samba
    networks:
      - adwebmanagerapp.net

networks:
  adwebmanagerapp.net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24

volumes:
  adwebmanagerapp.pgvol:
  adwebmanagerapp.pgadminvol:
