# version: '3.4'

services:
  samba:
    build:
      dockerfile: samba.Dockerfile
      args:
        samba_version: '4.16.7' #value selected from https://download.samba.org/pub/samba/stable
    image: admanager.directory:latest
    container_name: admanager.directory
    environment:
      SAMBA_DC_REALM: ${SAMBA_DC_REALM}
      SAMBA_DC_DOMAIN: ${SAMBA_DC_DOMAIN}
      SAMBA_DC_ADMIN_PASSWD: ${SAMBA_DC_ADMIN_PASSWD}
      SAMBA_DC_DNS_BACKEND: ${SAMBA_DC_DNS_BACKEND}
    restart: unless-stopped
    ports:
      - 636:636
      - 389:389
    networks:
      admanager.net:
        ipv4_address: 172.16.239.12

  db:
    image: postgres:16.2-alpine3.19
    container_name: admanager.db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - admanager.pgvol:/var/lib/postgresql/data
    networks:
      - admanager.net

  pgadmin:
    container_name: admanager.pgadmin
    image: dpage/pgadmin4:8.5
    env_file:
      - .env
    volumes:
      - admanager.pgadminvol:/var/lib/pgadmin
    ports:
      - 80:80
    networks:
      - admanager.net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: admanager.app:latest
    container_name: admanager.app
    ports:
      - 3000:3000
    depends_on:
      - db
      - samba
    networks:
      - admanager.net

networks:
  admanager.net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24

volumes:
  admanager.pgvol:
  admanager.pgadminvol:
