# version: '3.4'

services:
  samba:

    build:
      context: samba
      dockerfile: samba.Dockerfile
      args:
        samba_version: '4.16.7' #value selected from https://download.samba.org/pub/samba/stable
    image: admanager.directory:latest
    container_name: admanager.directory
    environment:
      SAMBA_DC_REALM: ${SAMBA_DC_REALM}
      SAMBA_DC_DOMAIN: ${SAMBA_DC_DOMAIN}
      SAMBA_DC_ADMIN_PASSWD: ${ADMIN_PASSWD}
      SAMBA_DC_DNS_BACKEND: ${SAMBA_DC_DNS_BACKEND}
    restart: unless-stopped
    ports:
      - 636:636
      - 389:389
    networks:
      admanager.net: # ipv4_address: 172.16.239.12
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: admanager.app:latest
    container_name: admanager.app
    ports:
      - 3000:3000
    depends_on:
      - samba
    networks:
      - admanager.net

networks:
  admanager.net:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.16.239.0/24
