/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Application configuration settings
 */
export interface Config {
	/**
	 * System settings
	 */
	system: {
		/**
		 * Logging settings
		 */
		logging: {
			/**
			 * Enable or disable logging. If `false` `basePath` is ignored. If `true` `basePath` is required @default ./logs
			 */
			useLogging: boolean;
			/**
			 * Log template as indicated by @link https://www.npmjs.com/package/sveltekit-logger-hook @default "[{date}] {url}{urlSearchParams} {method} {status}"
			 */
			logTemplate?: string;
			/**
			 * Log date template as indicated by @link https://day.js.org/docs/en/display/format @default "YYYY-MM-DD HH:mm:ss A"
			 */
			logDateTemplate?: string;
			/**
			 * Enable or disable url search params decoding. @default false
			 */
			decodeSearchParams?: boolean;
			/**
			 * Logging paths. Where the app and system logs will be stored
			 */
			basePath?: string;
		};
	};
	/**
	 * Interface configuration settings
	 */
	app: {
		/**
		 * configuration reggarding de different pages of the web app
		 */
		views: {
			/**
			 * configuration reggarding the logs page
			 */
			logsPage: {
				/**
				 * Weather or not to show the /logs page in navigation. Accessing directly to this route will result on a '403 This page has been disabled by configuration' error
				 */
				show?: boolean;
			};
		};
		/**
		 * Length of the captcha shown in the authentication page, recommended to use a low value for development.5
		 */
		captchaLength?: number;
	};
	/**
	 * Directory management configuration settings
	 */
	directory: {
		/**
		 * Directory settings reggarding user management
		 */
		users: {
			/**
			 * The list of user distinguishedNames or sAMAccountNames that should not be shown in the list view and dropdowns]
			 */
			hide: string[];
			/**
			 * The maximum amount of users allowed in the directory. If set to null the limit will be ignored.l
			 */
			limit: number | null;
		};
		/**
		 * Directory settings reggarding group management
		 */
		groups: {
			/**
			 * The list of group distinguishedNames or sAMAccountNames that should not be shown in the list view and dropdowns]
			 */
			hide: string[];
			/**
			 * The maximum amount of groups allowed in the directory. If set to null the limit will be ignored.l
			 */
			limit: number | null;
		};
	};
	[k: string]: unknown;
}
