/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Config {
	/**
	 * Application configuration settings
	 */
	app: {
		/**
		 * Length of the captcha shown in the authentication page, recommended to use a low value for development.
		 *
		 * @default 5
		 */
		captcha_length?: number;
		[k: string]: unknown;
	};
	/**
	 * Directory configuration settings
	 */
	directory: {
		/**
		 * The maximum amount of users allowed in the directory. If set to null the limit will be ignored.
		 *
		 * @default null
		 */
		user_limit?: number | null;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}
